#             _   _                           
#  _ __ _   _| |_| |__   ___   ___ ___  _ __  
# | '__| | | | __| '_ \ / _ \ / __/ _ \| '_ \ 
# | |  | |_| | |_| | | | (_) | (_| (_) | |_) |
# |_|   \__,_|\__|_| |_|\___/ \___\___/| .__/ 
#                                      |_|   

Metrics/BlockLength:
  Exclude:
    - 'spec/*'

Metics/LineLength:
  Exclude:
    - 'spec/spec_helper.rb'
